#!/bin/bash

set -e

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IP=`cat $DIR/node_ip_address.txt`

$DIR/stop

echo 'Copying files...'
FILES=( 'package.json' 'package-lock.json' 'app.js' )
for FILE in "${FILES[@]}"; do
    scp -i $DIR/../key.pem $DIR/$FILE ec2-user@$IP:~/app/$FILE
done

echo 'Installing dependencies...'
$DIR/remote 'cd app && npm i'

$DIR/start
