#!/bin/bash

set -e

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IP=$1

if [[ -z $IP ]]; then
    IP=`cat $DIR/ip`
fi;

echo "using IP $IP..."

$DIR/stop $IP

$DIR/remote $IP "\
    echo 'Downloading updated src' && \
    curl https://s3.amazonaws.com/tp-arqui-node-app-src/src.zip > src.zip && \
    echo 'Unpacking src code' && \
    unzip src.zip  && \
    echo 'Installing dependencies' && \
    npm i"

$DIR/start $IP
